### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by johnpmayer** [mrosset/go-git#1]
<pre>
jpmayer@------ ~/go-git
 % go build
# _/home/jpmayer/go-git
1: error: 'git_index_open_inrepo' undeclared (first use in this function)
1: note: each undeclared identifier is reported only once for each function it appears in
1: error: 'git_oid_mkstr' undeclared (first use in this function)
1: error: 'git_tree_close' undeclared (first use in this function)
</pre>

In addition, I preferred to install libgit2 following the cmake instructions; waf didn't work out of the box and wasn't playing nice when I installed it myself. This was on Ubuntu 11.10 on AWS.

You should also note that libssl is required for libgit2, I got a build error when libcrypto was missing.

edit: This also occurs when doing `go get`

**Comment by johnpmayer** [comment]
<pre>

 % make
make: *** pkg/git: No such file or directory.  Stop.
make: *** [test] Error 2

</pre>


Finally, this is what happened when using the existing Makefile.

**Comment by mrosset** [comment]
thanks for this issue. I'll look into easing the install process.

**Comment by mrosset** [comment]
@johnpmayer I've updated install instructions. the api is frozen to libgit 0.12.0 that should resolve the undeclared function issue.

**Comment by mrosset** [comment]
moving to issue #2. apologies for this taking so long.
